/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.skillfactory.shadow;
import com.google.common.collect.Lists;

import java.util.List;

public class App {
    public String getGreeting() {
        //return StringUtils.upperCase("Hello World!");
        List<String> greeting = Lists.newArrayList("Hellow", "World", "!");
        return greeting.toString();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
