/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_dep;

import com.google.common.collect.Lists;
import org.apache.commons.lang3.StringUtils;

import java.util.List;

public class App {
    public String getGreeting() {
        return StringUtils.upperCase("Hello World!");
        //List<String> greeting = Lists.newArrayList("Hellow", "World", "!");
        //return greeting.toString();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
